version: '3'

volumes:
  postgres_data_local: {}
  postgres_data_local_backups: {}

services:
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: postgres
    container_name: postgres
    volumes:
      - postgres_data_local:/var/lib/postgresql/data:Z
      - postgres_data_local_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres